# Generated by Django 4.0 on 2022-01-13 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=50)),
                ('cat_img', models.ImageField(blank='True', default='', null='True', upload_to='cat_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_title', models.CharField(max_length=200)),
                ('rec_details', models.TextField()),
                ('rec_img1', models.ImageField(blank='True', default='', null='True', upload_to='images/')),
                ('rec_img2', models.ImageField(blank='True', default='', null='True', upload_to='images/')),
                ('rec_img3', models.ImageField(blank='True', default='', null='True', upload_to='images/')),
                ('rec_img4', models.ImageField(blank='True', default='', null='True', upload_to='images/')),
                ('rec_preptime', models.CharField(max_length=100)),
                ('rec_cooktime', models.CharField(max_length=100)),
                ('rec_ingredients', models.CharField(blank='True', max_length=200, null='True')),
                ('rec_directions', models.CharField(blank='True', max_length=100, null='True')),
                ('rec_nutfacts', models.CharField(blank='True', max_length=100, null='True')),
                ('rec_servings', models.IntegerField()),
                ('rec_type', models.CharField(choices=[(1, 'Chinese'), (2, 'Afghani'), (3, 'Indian'), (4, 'Dubai')], max_length=50)),
                ('rec_posteddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('rec_catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.IntegerField()),
                ('posteddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.recipe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
