# Generated by Django 4.0 on 2022-01-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_recipe_rec_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_type',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('Afghani', 'Afghani'), ('Indian', 'Indian'), ('Dubai', 'Dubai')], max_length=50),
        ),
    ]
