# Generated by Django 4.0 on 2022-01-28 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_recipe_rec_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_nutfacts',
            field=models.CharField(blank='True', max_length=300, null='True'),
        ),
    ]
