# Generated by Django 4.0 on 2022-01-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_recipe_rec_nutfacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_directions',
            field=models.CharField(blank='True', max_length=500, null='True'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rec_ingredients',
            field=models.CharField(blank='True', max_length=500, null='True'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rec_nutfacts',
            field=models.CharField(blank='True', max_length=500, null='True'),
        ),
    ]
