# Generated by Django 4.0 on 2022-01-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_recipe_rec_directions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rec_directions',
            field=models.CharField(blank='True', max_length=1000, null='True'),
        ),
    ]
