# Generated by Django 4.0 on 2022-02-16 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0006_alter_recipe_rec_directions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_info', models.CharField(blank=True, max_length=500, null=True)),
                ('user_fname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_lname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
